/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TacoTable {
        "columns": { title: string; id: string; hasSorting: BooleanConstructor; class: string; }[];
        "rows": [any];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTacoTableElement extends Components.TacoTable, HTMLStencilElement {
    }
    var HTMLTacoTableElement: {
        prototype: HTMLTacoTableElement;
        new (): HTMLTacoTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "taco-table": HTMLTacoTableElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TacoTable {
        "columns"?: { title: string; id: string; hasSorting: BooleanConstructor; class: string; }[];
        "rows"?: [any];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "taco-table": TacoTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "taco-table": LocalJSX.TacoTable & JSXBase.HTMLAttributes<HTMLTacoTableElement>;
        }
    }
}
